/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;

/**
 *
 * @author vidur
 */
public class HomeUI extends javax.swing.JFrame//inheritance jframe is the parent class of ui
{

    /**
     * Creates new form HomeUI
     */
    public HomeUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        btnhelp = new javax.swing.JButton();
        lblHelp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDate.setFont(new java.awt.Font("Goudy Old Style", 0, 12)); // NOI18N
        lblDate.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblDateMouseMoved(evt);
            }
        });
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 140, 23));

        lbltime.setFont(new java.awt.Font("Goudy Old Style", 0, 12)); // NOI18N
        jPanel1.add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 140, 19));

        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        jLabel2.setText("DATE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        login.setBackground(new java.awt.Color(251, 251, 235));
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/generatedtextPLAYw.png"))); // NOI18N
        login.setText("PLAY");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 190, 70));

        btnhelp.setBackground(new java.awt.Color(252, 252, 236));
        btnhelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/ss (2).png"))); // NOI18N
        btnhelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhelpActionPerformed(evt);
            }
        });
        jPanel1.add(btnhelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 190, 80));

        lblHelp.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        lblHelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 370, 23));

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        jLabel1.setText("TIME");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/generatedtext_1.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 430, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/—Pngtree—cute hand drawn style mathematics_1176971.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1110, -10, 1820, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhelpActionPerformed
 String tx ="Hello, pleese login to your account ,Aand enjoy the game ,You will get riddles you can solve them and see your scores";
 lblHelp.setText("Enter User Name And Password");
 Voice voice;//object
 VoiceManager vm =  VoiceManager.getInstance();//object from voice class
     
        voice = vm.getVoice("kevin16");//method
        
        voice.allocate();
        
        voice.speak(tx);        
// TODO add your handling code here:
    }//GEN-LAST:event_btnhelpActionPerformed
//www.worldtimeapi.com
    private void lblDateMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDateMouseMoved
   try (java.util.Scanner s = new java.util.Scanner(new java.net.URL("http://worldtimeapi.org/api/Asia/Colombo").openStream(), "UTF-8").useDelimiter("\\A")) {
           
       //abstract
       String x = s.next();
            System.out.println("today date " + x);
 
            String[] Xsplit =x.split(",");
   
            String dateApi = ( Xsplit[2].split("\"") )[3];
    
            String[] dateAndTime = dateApi.split("T");

            System.out.println( dateAndTime[0] );
            lbltime.setText(dateAndTime[0]);
            lblDate.setText(dateAndTime[1]);
               
   
        } catch (Exception e) {
           e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_lblDateMouseMoved

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
                dispose();
              LoginUi d = new LoginUi();
              d.setLocationRelativeTo(null);
              d.setTitle("Login");
              d.setVisible(true );           // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lbltime;
    private javax.swing.JButton login;
    // End of variables declaration//GEN-END:variables
}
