/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Code.ChartUI;
import Code.DBConnection;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author vidur
 */
//build in inheritance

public class level1 extends javax.swing.JFrame {
    //extends from jrame class inheriance
      
//DBConnection conn;
String  [] questions = {"I am a 3 digit number.My 2nd digit is 4 times bigger than the 3rd digit.My 1st digit is 3 less than my 2nd digit. What number am I?",
    "There are books on a bookshelf.If one book is the 14th from the left and 16th from the right,how many books are on the shelf?",
    "2 + 2 comes to the same as 2 × 2. Find a set of 3 different whole numbers whose sum is equal to their total when multiplied.",
    "What is the smallest whole number that is equal to seven times the sum of its digits?",
    "What is the smallest number that increases by 12 when it is flipped and turned upside down?",
    "people in front of 2 people,2 people behind 2 people and 2 people beside 2 people.How many people are there?",
    "The day before yesterday I was 21, and the next year, I will be 24. What day is my birthday? ",
    "When John was 8, his brother was half his age. Now that John is 14, how old is his brother? ",
    "Hary is 54 years old, and his mother Anna is 80. How many years ago was Anna there times the age of her son hary?",
    "A number is decreased by 40% and gives 180, find the number?"
    
};
String [][] options =  {{"141","200","120","60","141"},
    {"24","29","40","14","29"},
    {"2,3,4","1,2,3","7,8,9","7,4,1","1,2,3"},
    {"12","15","10","21","21"},
    {"84","32","86","80","86"},
    {"4","5","7","2","4"},
    {"29th December ","31st December","1st October ","25th December ","31st December"},
    {"10","5","11","12","10"},
    {"42 years ago","50 years ago","41 years ago","40 years ago","41 years ago"},
    {"150","160","180","170","180"},
};
String [] level = {"level 1","level 2","level 3","level 4","level 5","level 6","level 7","level 8","level 9","level 10"};
int index=0;
int correct =0;
int correctA=0;
ButtonGroup bg = new ButtonGroup();//object
    public level1() {
        initComponents();
        
          String passUname = LoginUi.passUsername();
          lblusername.setText(passUname);
          
        scaleImage();
  
        bg.add(jRadioButton1);
        bg.add(jRadioButton2);
        bg.add(jRadioButton3);
        bg.add(jRadioButton4);
       
        
    }
    //constructor metod
    private void scaleImage(){
    ImageIcon icon = new ImageIcon("C:\\Users\\vidur\\Documents\\NetBeansProjects\\RiddleGames\\src\\UI\\next.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        label.setIcon(scaledIcon);
    }
    
    public void getSelectedOption(JRadioButton rbtn){
    System.out.println(rbtn.getText());
    System.out.println(options[index][4]);
    
    if(rbtn.getText().equals(options[index][4]))
    {
        correct++;
    }
        index++;  
    enableRbuttons(false);
    }
    
    public void enableRbuttons(boolean yes_or_no){
    jRadioButton1.setEnabled(yes_or_no);
    jRadioButton2.setEnabled(yes_or_no);
    jRadioButton3.setEnabled(yes_or_no);
    jRadioButton4.setEnabled(yes_or_no);
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblusername = new javax.swing.JLabel();
        lbllevel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_question = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        lblnextquestion = new javax.swing.JLabel();
        checkpie = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblusername.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        jPanel1.add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 170, 30));

        lbllevel.setBackground(new java.awt.Color(0, 0, 0));
        lbllevel.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        jPanel1.add(lbllevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 150, 48));

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 3, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/generatedtext_1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, 80));

        lbl_question.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lbl_question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 57, 1020, 110));

        jRadioButton1.setBackground(new java.awt.Color(204, 255, 255));
        jRadioButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 183, -1));

        jRadioButton2.setBackground(new java.awt.Color(204, 255, 255));
        jRadioButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 183, -1));

        jRadioButton3.setBackground(new java.awt.Color(204, 255, 255));
        jRadioButton3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 183, -1));

        jRadioButton4.setBackground(new java.awt.Color(204, 255, 255));
        jRadioButton4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 183, -1));

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 0, 14)); // NOI18N
        jLabel1.setText("1.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Goudy Old Style", 0, 14)); // NOI18N
        jLabel3.setText("2.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Goudy Old Style", 0, 14)); // NOI18N
        jLabel4.setText("3.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 10, -1));

        jLabel5.setFont(new java.awt.Font("Goudy Old Style", 0, 14)); // NOI18N
        jLabel5.setText("4.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, -1));

        label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMouseClicked(evt);
            }
        });
        jPanel1.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 160, 70));

        lblnextquestion.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblnextquestion.setText("NEXT");
        jPanel1.add(lblnextquestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 210, 30));

        checkpie.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        checkpie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkpie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkpie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkpieMouseClicked(evt);
            }
        });
        jPanel1.add(checkpie, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 444, 470, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/—Pngtree—cute hand drawn style mathematics_1176971.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 10, 1180, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
          getSelectedOption(jRadioButton2); // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        getSelectedOption(jRadioButton4);  // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
         getSelectedOption(jRadioButton1);  // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
         getSelectedOption(jRadioButton3);  // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMouseClicked
      if(lblnextquestion.getText().equals("Restart the quiz"))
      {
      lblnextquestion.setText("NEXT");
             jPanel1.setBackground(new java.awt.Color(204, 204, 204));
             index=0;
              correct=0;
      }
         if(index == questions.length){
             lbl_question.setText("Your Score" + correct + " / " + questions.length);
             checkpie.setText("Check Score With pieChart");
              correctA= correct*10;
                
              setScore(correctA);
                 if(correct >=(float)questions.length/2)
                     {
                        jPanel1.setBackground(Color.green);
                 }else{
                
                jPanel1.setBackground(Color.CYAN);
               
                
         }
         lblnextquestion.setText("Restart the quiz");
       }else{
       
            enableRbuttons(true);
            lbl_question.setText(questions[index]); 
            lbllevel.setText(level[index]);
            jRadioButton1.setText(options[index][0]);
            jRadioButton2.setText(options[index][1]);
            jRadioButton3.setText(options[index][2]);
            jRadioButton4.setText(options[index][3]);
             if(index == questions.length-1){
                lblnextquestion.setText("finish and see the results");
            }
         
        }bg.clearSelection();
         
    }//GEN-LAST:event_labelMouseClicked

    private void checkpieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkpieMouseClicked
    dispose();
    ChartUI s = new ChartUI();
    s.setLocationRelativeTo(null);
    s.setVisible(true);
    }//GEN-LAST:event_checkpieMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(level1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(level1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(level1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(level1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new level1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel checkpie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lbl_question;
    private javax.swing.JLabel lbllevel;
    private javax.swing.JLabel lblnextquestion;
    private javax.swing.JLabel lblusername;
    // End of variables declaration//GEN-END:variables

    private void setScore(int correctA) {
    DBConnection con = new DBConnection();
    Connection dbconn = con.connectDB(); 
          
    if (dbconn != null){
        try {
          String username = lblusername.getText();
         PreparedStatement st = (PreparedStatement)
                 
         dbconn.prepareStatement("update user set correct = ? where user.username ='"+ username +"'");
 
          st.setInt(1, correctA);
          int res = st.executeUpdate();
          System.out.println("user data updated"); 
         
         
        } catch (SQLException ex) {
            Logger.getLogger(LoginUi.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else{
        System.out.println("Connection not available"); 
    }
        
}
}
         
    
    

    

